export const heroWorkflow = [
  {
    id: "launch",
    title: "Launch App",
    subtitle: "Start Android Emulator",
    duration: 1200,
    log: "Launching application...",
    screen: "splash",
  },
  {
    id: "find-login",
    title: "Find Login Button",
    subtitle: "Locate accessibility id",
    duration: 900,
    log: "Login button found.",
    screen: "splash",
  },
  {
    id: "tap-login",
    title: "Tap Login",
    subtitle: "Navigate to Login",
    duration: 1000,
    log: "Opening login page.",
    screen: "login",
  },
  {
    id: "username",
    title: "Input Username",
    subtitle: "Type username",
    duration: 1500,
    log: "Typing username...",
    screen: "typing-username",
  },
  {
    id: "password",
    title: "Input Password",
    subtitle: "Type password",
    duration: 1500,
    log: "Typing password...",
    screen: "typing-password",
  },
  {
    id: "submit",
    title: "Tap Login Button",
    subtitle: "Submit credentials",
    duration: 1200,
    log: "Submitting login.",
    screen: "loading",
  },
  {
    id: "dashboard",
    title: "Assert Dashboard",
    subtitle: "Verify Home Screen",
    duration: 1800,
    log: "Dashboard verified.",
    screen: "dashboard",
  },
];
