import BaseNode from "./BaseNode";

export const nodeTypes = {
  launchApp: BaseNode,
  closeApp: BaseNode,
  tap: BaseNode,
  inputText: BaseNode,
  swipe: BaseNode,
  scroll: BaseNode,
  wait: BaseNode,
  longPress: BaseNode,
  doubleTap: BaseNode,
  drag: BaseNode,
  pinch: BaseNode,
  zoom: BaseNode,
  fling: BaseNode,
  hideKeyboard: BaseNode,
  pressReturn: BaseNode,
  back: BaseNode,
  home: BaseNode,
  delay: BaseNode,
  screenshot: BaseNode,
  getText: BaseNode,
  elementExists: BaseNode,
  getAttribute: BaseNode,
  getDisplayed: BaseNode,
  getEnabled: BaseNode,
  getSelected: BaseNode,
  getCurrentActivity: BaseNode,
  getCurrentPackage: BaseNode,
  getOrientation: BaseNode,
  getPlatformVersion: BaseNode,
  getDeviceName: BaseNode,
  getDeviceTime: BaseNode,
  getLocation: BaseNode,
  getSize: BaseNode,
  getRect: BaseNode,
  if: BaseNode,
  repeat: BaseNode,
  assert: BaseNode,
  setVariable: BaseNode,
};