import {
  FiSmartphone,
  FiMousePointer,
  FiType,
  FiClock,
  FiCheckCircle,
  FiRepeat,
  FiGitBranch,
  FiBox,
  FiChevronUp,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiSearch,
  FiCamera,
  FiHome,
  FiArrowLeft,
  FiArrowRight,
  FiZap,
  FiCommand,
  FiHash,
  FiToggleLeft,
  FiSliders,
  FiMapPin,
  FiMaximize,
  FiSquare,
  FiArrowDown,
  FiEye,
  FiInfo,
} from "react-icons/fi";

export const componentLibrary = [
  {
    title: "Application",
    items: [
      {
        type: "launchApp",
        title: "Launch App",
        subtitle: "Open an application",
        icon: FiSmartphone,
        color: "#6366f1",
      },
      {
        type: "closeApp",
        title: "Close App",
        subtitle: "Close an application",
        icon: FiSquare,
        color: "#6366f1",
      },
    ],
  },
  {
    title: "Element Actions",
    items: [
      {
        type: "tap",
        title: "Tap",
        subtitle: "Tap an element",
        icon: FiMousePointer,
        color: "#22c55e",
      },
      {
        type: "inputText",
        title: "Input Text",
        subtitle: "Type text",
        icon: FiType,
        color: "#3b82f6",
      },
      {
        type: "swipe",
        title: "Swipe",
        subtitle: "Swipe gesture",
        icon: FiArrowRight,
        color: "#8b5cf6",
      },
      {
        type: "scroll",
        title: "Scroll",
        subtitle: "Scroll to element",
        icon: FiArrowDown,
        color: "#8b5cf6",
      },
      {
        type: "wait",
        title: "Wait",
        subtitle: "Wait for element",
        icon: FiClock,
        color: "#eab308",
      },
      {
        type: "longPress",
        title: "Long Press",
        subtitle: "Press and hold",
        icon: FiMousePointer,
        color: "#22c55e",
      },
      {
        type: "doubleTap",
        title: "Double Tap",
        subtitle: "Tap twice",
        icon: FiMousePointer,
        color: "#22c55e",
      },
      {
        type: "drag",
        title: "Drag",
        subtitle: "Drag element",
        icon: FiArrowRight,
        color: "#8b5cf6",
      },
      {
        type: "pinch",
        title: "Pinch",
        subtitle: "Pinch gesture",
        icon: FiMaximize,
        color: "#8b5cf6",
      },
      {
        type: "zoom",
        title: "Zoom",
        subtitle: "Zoom gesture",
        icon: FiMaximize,
        color: "#8b5cf6",
      },
      {
        type: "fling",
        title: "Fling",
        subtitle: "Fling gesture",
        icon: FiZap,
        color: "#8b5cf6",
      },
      {
        type: "hideKeyboard",
        title: "Hide Keyboard",
        subtitle: "Dismiss keyboard",
        icon: FiChevronDown,
        color: "#8b5cf6",
      },
      {
        type: "pressReturn",
        title: "Press Return",
        subtitle: "Press return key",
        icon: FiCommand,
        color: "#8b5cf6",
      },
    ],
  },
  {
    title: "Device Actions",
    items: [
      {
        type: "back",
        title: "Back",
        subtitle: "Navigate back",
        icon: FiArrowLeft,
        color: "#f97316",
      },
      {
        type: "home",
        title: "Home",
        subtitle: "Go to home screen",
        icon: FiHome,
        color: "#f97316",
      },
      {
        type: "delay",
        title: "Delay",
        subtitle: "Pause execution",
        icon: FiClock,
        color: "#eab308",
      },
      {
        type: "screenshot",
        title: "Screenshot",
        subtitle: "Capture screen",
        icon: FiCamera,
        color: "#f97316",
      },
    ],
  },
  {
    title: "Element Getters",
    items: [
      {
        type: "getText",
        title: "Get Text",
        subtitle: "Read element text",
        icon: FiType,
        color: "#06b6d4",
      },
      {
        type: "elementExists",
        title: "Element Exists",
        subtitle: "Check if element exists",
        icon: FiSearch,
        color: "#06b6d4",
      },
      {
        type: "getAttribute",
        title: "Get Attribute",
        subtitle: "Read attribute value",
        icon: FiSliders,
        color: "#06b6d4",
      },
      {
        type: "getDisplayed",
        title: "Get Displayed",
        subtitle: "Is element visible",
        icon: FiEye,
        color: "#06b6d4",
      },
      {
        type: "getEnabled",
        title: "Get Enabled",
        subtitle: "Is element enabled",
        icon: FiToggleLeft,
        color: "#06b6d4",
      },
      {
        type: "getSelected",
        title: "Get Selected",
        subtitle: "Is element selected",
        icon: FiCheckCircle,
        color: "#06b6d4",
      },
    ],
  },
  {
    title: "Device Getters",
    items: [
      {
        type: "getCurrentActivity",
        title: "Get Current Activity",
        subtitle: "Current Android activity",
        icon: FiHash,
        color: "#10b981",
      },
      {
        type: "getCurrentPackage",
        title: "Get Current Package",
        subtitle: "Current package",
        icon: FiHash,
        color: "#10b981",
      },
      {
        type: "getOrientation",
        title: "Get Orientation",
        subtitle: "Screen orientation",
        icon: FiChevronUp,
        color: "#10b981",
      },
      {
        type: "getPlatformVersion",
        title: "Get Platform Version",
        subtitle: "OS version",
        icon: FiInfo,
        color: "#10b981",
      },
      {
        type: "getDeviceName",
        title: "Get Device Name",
        subtitle: "Device model",
        icon: FiSmartphone,
        color: "#10b981",
      },
      {
        type: "getDeviceTime",
        title: "Get Device Time",
        subtitle: "Current device time",
        icon: FiClock,
        color: "#10b981",
      },
      {
        type: "getLocation",
        title: "Get Location",
        subtitle: "GPS coordinates",
        icon: FiMapPin,
        color: "#10b981",
      },
      {
        type: "getSize",
        title: "Get Size",
        subtitle: "Screen dimensions",
        icon: FiMaximize,
        color: "#10b981",
      },
      {
        type: "getRect",
        title: "Get Rect",
        subtitle: "Element bounds",
        icon: FiSquare,
        color: "#10b981",
      },
    ],
  },
  {
    title: "Logic and Data",
    items: [
      {
        type: "if",
        title: "If",
        subtitle: "Conditional branch",
        icon: FiGitBranch,
        color: "#f59e0b",
      },
      {
        type: "repeat",
        title: "Repeat",
        subtitle: "Loop actions",
        icon: FiRepeat,
        color: "#f59e0b",
      },
      {
        type: "assert",
        title: "Assert",
        subtitle: "Verify condition",
        icon: FiCheckCircle,
        color: "#f97316",
      },
      {
        type: "setVariable",
        title: "Set Variable",
        subtitle: "Assign variable",
        icon: FiHash,
        color: "#f59e0b",
      },
    ],
  },
];
