const nodeTypes = [
  "launchApp",
  "closeApp",
  "tap",
  "inputText",
  "swipe",
  "scroll",
  "wait",
  "longPress",
  "doubleTap",
  "drag",
  "pinch",
  "zoom",
  "fling",
  "hideKeyboard",
  "pressReturn",
  "back",
  "home",
  "delay",
  "screenshot",
  "getText",
  "elementExists",
  "getAttribute",
  "getDisplayed",
  "getEnabled",
  "getSelected",
  "getCurrentActivity",
  "getCurrentPackage",
  "getOrientation",
  "getPlatformVersion",
  "getDeviceName",
  "getDeviceTime",
  "getLocation",
  "getSize",
  "getRect",
  "if",
  "repeat",
  "assert",
  "setVariable",
];

const defaultDurations = {
  launchApp: 1500,
  closeApp: 800,
  tap: 800,
  inputText: 900,
  swipe: 1000,
  scroll: 1000,
  wait: 1500,
  longPress: 1200,
  doubleTap: 800,
  drag: 1200,
  pinch: 1200,
  zoom: 1200,
  fling: 1000,
  hideKeyboard: 500,
  pressReturn: 500,
  back: 500,
  home: 500,
  delay: 1000,
  screenshot: 800,
  getText: 600,
  elementExists: 600,
  getAttribute: 600,
  getDisplayed: 600,
  getEnabled: 600,
  getSelected: 600,
  getCurrentActivity: 600,
  getCurrentPackage: 600,
  getOrientation: 600,
  getPlatformVersion: 600,
  getDeviceName: 600,
  getDeviceTime: 600,
  getLocation: 600,
  getSize: 600,
  getRect: 600,
  if: 700,
  repeat: 700,
  assert: 1000,
  setVariable: 600,
};

const customRunners = {
  launchApp: {
    start: "Launching application...",
    finish: "Application launched successfully.",
    duration: 1500,
  },
  tap: {
    start: "Tapping element...",
    finish: "Element tapped.",
    duration: 800,
  },
  inputText: {
    start: "Inputting text...",
    finish: "Text entered.",
    duration: 900,
  },
  assert: {
    start: "Verifying assertion...",
    finish: "Assertion passed.",
    duration: 1000,
  },
};

export const runners = Object.fromEntries(
  nodeTypes.map((type) => [
    type,
    customRunners[type] || {
      start: `Executing ${type}...`,
      finish: `${type} completed successfully.`,
      duration: defaultDurations[type] || 1200,
    },
  ]),
);
